export const selectOptions = [
  "ALL QUIET ON THE WESTERN FRONT",
  "EVERYTHING EVERYWHERE ALL AT ONCE",
  "AVATAR: THE WAY OF WATER",
  "THE BANSHEES OF INISHERIN",
  "ELVIS",
  "THE FABELMANS",
  "TÁR",
  "TOP GUN: MAVERICK",
  "TRIANGLE OF SADNESS",
  "WOMEN TALKING",
];
